name: epub
version: 1.2.9
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Web or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  async:
  archive:
  xml:
  image:
dev_dependencies:
  test:
  path:
